### ISSUE TITLE
Support file overwrite

### ISSUE THREAD

**Issue by kentcdodds** [amwmedia/plop#90] opened 2017-09-01 23:27 UTC
With yeoman, if there's a file already in place and you want to write a file there, it will ask the user if they'd like to overwrite it. Is that a feature plop could have?

**Comment by amwmedia** [comment] 2017-09-02 04:40
It is certainly a possibility. I haven't seen it as a high priority so far because it seems to me that 90% of the time if my generator is going to overwrite something that is pre-existing, it means I need to backup and provide different input. Can you think of a real-world scenario where you'd want to actually overwrite?

**Comment by amwmedia** [comment] 2017-09-02 04:43
this is a duplicate of #32.

**Closed by amwmedia** 2017-09-02 04:43 UTC
Labels: duplicate
