### ISSUE TITLE
Do not update to node 8.1, prompts stuck

### ISSUE THREAD

**Issue by popul** [amwmedia/plop#75] opened 2017-06-13 20:06 UTC
Since i updated node to 8.1, prompts stuck forever.

Inquirer raise an issue https://github.com/nodejs/node/issues/13557

It seems to be a node issue https://github.com/SBoudrias/Inquirer.js/issues/547

With node 8.0, it works

**Comment by amwmedia** [comment] 2017-06-13 20:22
I just verified. node 8.0 (stable) works fine, node 8.1 (latest) freezes when the user needs to enter input. Thanks for bringing this up @popul 👍

**Comment by kubal5003** [comment] 2017-06-14 08:36
I also encountered this issue - Node 8.1 freezes, downgrade to 7.10 resolved the issue.

**Comment by styfle** [comment] 2017-06-14 12:17
I think this is fixed in Node 8.1.1 but I haven't verified yet.

**Comment by amwmedia** [comment] 2017-06-14 12:20
confirmed! a patch went out yesterday. 8.1.1 works for me.

**Closed by amwmedia** 2017-06-14 12:20 UTC

**Comment by rstacruz** [comment] 2017-06-17 21:19
I'm getting this error again in Node v8.1.2, sorry guys :(

**Comment by amwmedia** [comment] 2017-06-17 21:21
I just tried it with node 8.1.2 and wasn't able to reproduce ☹️
